schema_version: 1

context:
  version: "0.15.0"
  python_min: "3.11"

package:
  name: gpjax
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gpjax/gpjax-${{ version }}.tar.gz
  sha256: df54dd65f5479968410392aced0e301365def85438367cf8b5d5123ef16bd2e6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - jax >=0.5.0
    - jaxlib >=0.5.0
    - optax >0.2.1
    - numpyro
    - jaxtyping >0.2.10
    - tqdm >4.66.2
    - beartype >0.16.1
    - flax >=0.10.0
    - numpy >=2.0.0

tests:
  - python:
      imports:
        - gpjax
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Gaussian processes in JAX.
  license: MIT
  license_file: LICENSE.txt
  homepage: https://github.com/JaxGaussianProcesses/GPJax
  repository: https://github.com/JaxGaussianProcesses/GPJax
  documentation: https://docs.jaxgaussianprocesses.com/

extra:
  recipe-maintainers:
    - thomaspinder
